# Generated by Django 5.2.12 on 2026-03-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_blockeduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='blocked_until',
        ),
    ]
